## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.1
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - python3
    - python3-pip
before_script: # homebrew for mac
   # install spinedatabase_api
   - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/Spine-project/SpineInterface.jl.git"));
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/Spine-project/SpineModel.jl.git")); Pkg.build("SpineModel")'
after_success:
  - julia 'using Pkg; Pkg.add("Documenter")'
  - julia --color=yes -e 'using SpineModel; include(joinpath(pathof(SpineModel), "..", "..", "docs", "make.jl"))'
