# GitHub Action

name: CI

# Run workflow on every push
on:
  push

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.2"  # Minimum compatible Release
          - "1.5"  # Latest Release
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
          - x86
        exclude:
          # Test 32-bit only on Linux
          - os: macOS-latest
            arch: x86
          - os: windows-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er
      - name: Add SpineJuliaRegistry
        run:
          julia -e 'using Pkg; pkg"registry add General"; pkg"registry add https://github.com/Spine-project/SpineJuliaRegistry"'
      - name: Install spinedb_api
        run: |
          julia -e 'using Pkg; Pkg.add("PyCall")'
          julia -e 'using PyCall; python = PyCall.pyprogramname; run(`$python -m pip install --user setuptools`)'
          julia -e 'using PyCall; python = PyCall.pyprogramname; run(`$python -m pip install --user git+https://github.com/Spine-project/Spine-Database-API`)'
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
